### ISSUE TITLE
"Link is removed or doesn't exist" while trying to fetch particular Link

### ISSUE THREAD

**Issue by pawel3ala** [Vegann/wykop-v2-typescript#127]
First things first: great idea to create a handy wrapper for shitty wykop API. Big hive five guys!

so here is my code:

```
  const wykop = new Wykop({
    appKey: 'dupamaryna',
    appSecret: 'abracadabra'
 });
  
  wykop.request({
    methods: ['Links', 'Link'],
    namedParams: { withcomments: true, id: 5714505 }
  }).then((res) => {
    console.log(res)
  }).catch((error) => {
    console.error(error)
  });
```

POST request is successfully sent but all I get is: 

`{code: 41, field: null, message_en: "Link is removed or doesn't exist", message_pl: "Brak znaleziska"}
`
The Link DO exist! Am I missing something?

**Comment by Vegann** [comment]
Hello!
Sorry for the very late response.
So, first thing first you should move `id` to `apiParams`. 
Second thing Wykop documentation is, of course, wrong with how we should order params. Right now when we are making this call: 
```js
  wykop.request({
    methods: ['Links', 'Link'],
    namedParams: { withcomments: true},
    apiParams: ["5714505"]
  }).then((res) => {
    console.log(res)
  }).catch((error) => {
    console.error(error)
  });
```
This lib generates this URL: `https://a2.wykop.pl/Links/Link/withcomments/true/5714505/appkey/dupadupa/`, and according to [documentation](https://www.wykop.pl/dla-programistow/apiv2docs/package/Links/#pLinks_Link) it should work, but the valid link should swap `withcomments` and `id` and valid link should look like this `https://a2.wykop.pl/Links/Link/5714505/withcomments/true/appkey/dupadupa/`.
I'll provide a fix to avoid bugs like this in the future.
